# Generated by Django 4.1.3 on 2022-12-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_program_product_product_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='https://cdn.admitad-connect.com/campaign/images/2020/10/16/251-ddd08a99b3e03533.png', null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
